const data = [
    {
        id: "uid1",
        name: "Kevin Hector",
        email: "kevinhector@athensai.com",
        nationalId: "12345678",
        gender: "Male",
        dob: "1st October 2000",
        joined: "2024-10-01T08:00:00Z",
        status: "unverified",
        role: "IT Support",
    },
    {
        id: "uid2",
        name: "Arap Too",
        email: "araptoo@athensai.com",
        nationalId: "23456789",
        gender: "Male",
        dob: "11th November 2000",
        joined: "2024-09-11T01:00:00Z",
        status: "unverified",
        role: "Customer Service",
    },
    {
        id: "uid3",
        name: "Amos",
        email: "amos@athensai.com",
        nationalId: "34567890",
        gender: "Male",
        dob: "22 February 1995",
        joined: "2024-10-14T09:00:00Z",
        status: "unverified",
        role: "HR",
    },
    {
        id: "uid4",
        name: "Janet Nyaga",
        email: "janetnyaga@athensai.com",
        nationalId: "45678901",
        gender: "Female",
        dob: "5th June 1990",
        joined: "2024-05-21T10:30:00Z",
        status: "verified",
        role: "Finance",
    },
    {
        id: "uid5",
        name: "Chris Ndirangu",
        email: "chrisndirangu@athensai.com",
        nationalId: "56789012",
        gender: "Male",
        dob: "17th August 1988",
        joined: "2023-12-20T11:45:00Z",
        status: "verified",
        role: "Manager",
    },
    {
        id: "uid6",
        name: "Susan Wambui",
        email: "susanwambui@athensai.com",
        nationalId: "67890123",
        gender: "Female",
        dob: "9th September 1992",
        joined: "2024-06-01T14:00:00Z",
        status: "unverified",
        role: "Customer Service",
    },
    {
        id: "uid7",
        name: "Peter Kamau",
        email: "peterkamau@athensai.com",
        nationalId: "78901234",
        gender: "Male",
        dob: "3rd December 1985",
        joined: "2024-03-17T07:15:00Z",
        status: "verified",
        role: "Finance",
    },
    {
        id: "uid8",
        name: "Lucy Wangari",
        email: "lucywangari@athensai.com",
        nationalId: "89012345",
        gender: "Female",
        dob: "12th May 1998",
        joined: "2024-08-02T13:25:00Z",
        status: "unverified",
        role: "IT Support",
    },
    {
        id: "uid9",
        name: "David Otieno",
        email: "davidotieno@athensai.com",
        nationalId: "90123456",
        gender: "Male",
        dob: "14th April 1996",
        joined: "2024-07-14T09:45:00Z",
        status: "unverified",
        role: "HR",
    },
    {
        id: "uid10",
        name: "Mary Mwangi",
        email: "marymwangi@athensai.com",
        nationalId: "01234567",
        gender: "Female",
        dob: "29th July 1993",
        joined: "2024-01-05T15:00:00Z",
        status: "verified",
        role: "Manager",
    },
    {
        id: "uid11",
        name: "Angela Chebet",
        email: "angelachebet@athensai.com",
        nationalId: "12345679",
        gender: "Female",
        dob: "22nd January 1994",
        joined: "2024-10-10T11:00:00Z",
        status: "verified",
        role: "Finance",
    },
    {
        id: "uid12",
        name: "John Mwenda",
        email: "johnmwenda@athensai.com",
        nationalId: "98765432",
        gender: "Male",
        dob: "4th March 1991",
        joined: "2024-09-15T08:30:00Z",
        status: "unverified",
        role: "Customer Service",
    }
];

export default data;
